# Generated by Django 4.2.2 on 2023-06-22 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_newsletter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAndQ',
            new_name='FAQ',
        ),
    ]
