# Generated by Django 4.2.2 on 2023-06-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='icon_class',
            field=models.CharField(choices=[('facebook', 'ri-facebook-fill'), ('twitter', '"ri-twitter-fill'), ('instagram', 'ri-instagram-fill'), ('linkedin', 'ri-linkedin-box-fill')], max_length=100),
        ),
    ]
