# Generated by Django 4.2.2 on 2023-06-22 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_social_icon_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='home.member'),
        ),
    ]
