# Generated by Django 4.2.2 on 2023-06-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_servicerequest_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.AlterField(
            model_name='social',
            name='icon_class',
            field=models.CharField(choices=[('facebook', 'ri-facebook-fill'), ('twitter', 'ri-twitter-fill'), ('instagram', 'ri-instagram-fill'), ('linkedin', 'ri-linkedin-box-fill')], max_length=100),
        ),
    ]
