# Generated by Django 4.0.3 on 2023-06-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_aboutustext_companydetails_contactnowtext_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headdetails',
            name='image',
        ),
        migrations.RemoveField(
            model_name='headdetails',
            name='map_link',
        ),
        migrations.AddField(
            model_name='companydetails',
            name='map_link',
            field=models.CharField(default='#', max_length=500),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='facebook_link',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='instagram_link',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='linkedin_link',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='twitter_link',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AlterField(
            model_name='headdetails',
            name='video_link',
            field=models.CharField(default='#', max_length=500),
        ),
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
