# Generated by Django 4.2.2 on 2023-06-30 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_headdetails_image_remove_headdetails_map_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='is_head_image',
        ),
    ]
